#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

timezone="$(timedatectl show --value --property=Timezone)"

ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M
ynh_app_setting_set_default --key=php_post_max_size --value=100M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# SETUP APPLICATION
#=================================================
ynh_script_progression "Setting up $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console galette:install --dbtype=pgsql --dbhost=localhost --dbport=5432 --dbname="$db_name" --dbprefix="galette_" --dbuser="$db_user" --dbpass=$"$db_pwd" --admin=$admin --password=$password --no-interaction
popd

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown $app  $install_dir/galette/config
chmod g+rwx $install_dir/galette/config

for folder in attachments cache exports files imports logs photos templates_c tempimages
do
   chown $app  $install_dir/galette/data/$folder
   chmod g+rwx $install_dir/galette/data/$folder
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
