#!/bin/bash

app=galette
db_user=galette
db_name=galette

root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting galette domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/$app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
