#!/bin/bash

app=galette
db_user=galette
db_name=galette

root_pwd=$(cat /etc/yunohost/mysql)
domain=$(yunohost app setting galette domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
rm -rf /var/www/$app
rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
service nginx reload
yunohost app ssowatconf
