#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

timezone="$(timedatectl show --value --property=Timezone)"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/php/$php_version/fpm/pool.d/$app.conf"

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE USER RIGHTS
#=================================================

chown "$app" "$install_dir/galette/config"
chmod 750 "$install_dir/galette/config"

for folder in attachments cache exports files imports logs photos templates_c tempimages
do
    chown "$app" "$install_dir/galette/data/$folder"
    chmod 775 "$install_dir/galette/data/$folder"
done

#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression "Reloading NGINX web server and PHP-FPM..."

ynh_systemctl --service=php$php_version-fpm --action=reload
ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
