#!/bin/bash


source /usr/share/yunohost/helpers

timezone="$(timedatectl show --value --property=Timezone)"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="galette/config/config.inc.php galette/data galette/plugins"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown "$app" "$install_dir/galette/config"
chmod 750 "$install_dir/galette/config"

for folder in attachments cache exports files imports logs photos templates_c tempimages
do
    chown "$app" "$install_dir/galette/data/$folder"
    chmod 775 "$install_dir/galette/data/$folder"
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
